config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'answer', to: 'pages#answer'
  root to: 'pages#home', as: :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def answer
    @query = params[:query]
    @coach_answer = ''
    if @query == 'I am going to work'
      @coach_answer == 'Great!'
    elsif @query.include?('?')
      @coach_answer = 'Silly question, get dressed and go to work!'
    else
      @coach_answer = "I don't care, get dressed and go to work!"
    end
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/answer.html.erb
<div class="container">
<h1>Stupid Coaching</h1>
<div class = "borderleft">
  <div class="m-3">
    <%= @query %>
    <p class="em">- You</p>
  </div>
</div>

<div class="borderleft bcolor">
<div class="m-3">
  <strong><%= @coach_answer %></strong>
  <p class="em"> -Your Coach</p>
  </div>
</div>

<%= link_to "Ask a new question", home_path, class: "text-deco" %>
</div>

app/views/pages/home.html.erb
<div class ="container">
<h1>Stupid Coach</h1>
<p>Ask your coach anything</p>
<form class="d-flex" action="/answer" data-turbo="false">
  <input class="form-control w-50" type="text" name="query">
  <input class="btn btn-primary display-inline" type="submit" value="Ask!">
</form>
</div>